server:
  port: 8081
  error:
    include-message: always
  servlet:
    context-path: /phobos-api

spring:
  application:
    name: phobos

  jpa:
    show-sql: false
    open-in-view: false

  datasource:
    # Local host
#    url: jdbc:postgresql://localhost:5432/phobosdb

    # Mac db
    url: jdbc:postgresql://192.168.4.49:5432/phobosdb
    username: phobos
    password: Ph0bo$
    hikari:
      connection-timeout: 30000
      max-lifetime: 18000000
  web:
    resources:
      static-locations:
        - file:/phobos/
user:
  image:
    path: /phobos/images/users/
    preffix: /images/users/